## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

In [6]:
boston = datasets.load_boston()
x_train,x_test,y_train,y_test = train_test_split(boston.data,boston.target,test_size=0.2,random_state = 4)
regr = linear_model.LinearRegression()
regr.fit(x_train,y_train)
y_pred = regr.predict(x_test)

In [7]:
print(regr.coef_)

[-1.15966452e-01  4.71249231e-02  8.25980146e-03  3.23404531e+00
 -1.66865890e+01  3.88410651e+00 -1.08974442e-02 -1.54129540e+00
  2.93208309e-01 -1.34059383e-02 -9.06296429e-01  8.80823439e-03
 -4.57723846e-01]


In [8]:
print("Mean squared error: %.2f"%mean_squared_error(y_test,y_pred))

Mean squared error: 25.42


# Lasso for boston

In [16]:
boston = datasets.load_boston()
x_train,x_test,y_train,y_test = train_test_split(boston.data,boston.target,test_size=0.2,random_state = 4)
lasso = linear_model.Lasso(alpha=1.0)
lasso.fit(x_train,y_train)
y_pred = lasso.predict(x_test)

In [17]:
lasso.coef_

array([-0.06494981,  0.04581458, -0.        ,  0.        , -0.        ,
        1.18140024,  0.01109101, -0.73695809,  0.23350042, -0.01551065,
       -0.69270805,  0.00763157, -0.6927848 ])

In [18]:
print("Mean squared error %.2f"%mean_squared_error(y_test,y_pred))

Mean squared error 28.95


# Ridge for boston

In [20]:
boston = datasets.load_boston()
x_train,x_test,y_train,y_test = train_test_split(boston.data,boston.target,test_size=0.2,random_state = 4)
ridge = linear_model.Ridge(alpha=1.0)
ridge.fit(x_train,y_train)
y_pred = ridge.predict(x_test)

In [21]:
print(ridge.coef_)

[-1.12499445e-01  4.79562332e-02 -2.40438147e-02  2.96199458e+00
 -9.33966118e+00  3.93079015e+00 -1.73821202e-02 -1.43347691e+00
  2.75239392e-01 -1.38920708e-02 -8.31116943e-01  9.15637729e-03
 -4.66460539e-01]


In [22]:
print("Mean squared error %.2f"%mean_squared_error(y_test,y_pred))

Mean squared error 25.74


In [24]:
wine = datasets.load_wine()
x_train,x_test,y_train,y_test = train_test_split(wine.data,wine.target,test_size=0.2,random_state = 4)
regr = linear_model.LinearRegression()
regr.fit(x_train,y_train)
y_pred = regr.predict(x_test)

In [27]:
print(regr.coef_)

[-1.09099883e-01  1.67405249e-02 -2.18753671e-01  4.66803998e-02
  3.20692287e-04  1.24491691e-01 -3.26192950e-01 -1.91327414e-01
  3.72016066e-02  7.57429505e-02 -1.55979636e-01 -2.85946973e-01
 -7.51809245e-04]


In [26]:
print("Mean squared error %.2f"%mean_squared_error(y_test,y_pred))

Mean squared error 0.07


# Lasso for wine

In [31]:
wine = datasets.load_wine()
x_train,x_test,y_train,y_test = train_test_split(wine.data,wine.target,test_size=0.2,random_state = 4)
lasso = linear_model.Lasso(alpha=1.0)
lasso.fit(x_train,y_train)
y_pred = lasso.predict(x_test)

In [32]:
lasso.coef_

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.        , -0.        ,  0.        , -0.        ,  0.        ,
       -0.        , -0.        , -0.00159714])

In [33]:
print("Mean squared error %.2f"%mean_squared_error(y_test,y_pred))

Mean squared error 0.42


# Ridge for wine

In [34]:
wine = datasets.load_wine()
x_train,x_test,y_train,y_test = train_test_split(wine.data,wine.target,test_size=0.2,random_state = 4)
ridge = linear_model.Ridge(alpha=1.0)
ridge.fit(x_train,y_train)
y_pred = ridge.predict(x_test)

In [36]:
ridge.coef_

array([-0.1060308 ,  0.01767173, -0.20185208,  0.04519307,  0.00041456,
        0.09901609, -0.31237143, -0.1038379 ,  0.03489971,  0.07770768,
       -0.13450626, -0.27442063, -0.00077001])

In [37]:
print("Mean squared error %.2f"%mean_squared_error(y_test,y_pred))

Mean squared error 0.07
